version: "3.8"
services:
  bot:
    container_name: okbot_discord
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/okbot
      - /usr/src/okbot/node_modules
    command: yarn start
