version: "3.8"
services:
  bot:
    build: .
    env_file:
      - .env
  db:
    image: "mongo"
    expose:
      - "27017"
    volumes:
      - mongo-data:/db
    env_file:
      - .env

volumes:
  mongo-data:
